print('1. Basic Printing:')
print('Hello World!')
print('Abubakar')
print('2. Printing Multiple Items:')
print('Abubakar Amin')
print(1,2,3)
print('3. Printing Special Characters:')
print('Hello\nWorld!')
print('Hello\tWorld!')
print('4. Using the sep Parameter:')
print('apple','banana','cherry',sep=', ')
print(1,2,3,sep=' - ')
print('5. Using the end Parameter:')
print('Hello', end=" ")
print('World!')
print(1,end='')
print(2)
print('6. Escape Characters:')
print('"Hello!"')
print('Hello\\World!')
print('7. Combining Text and Numbers:')
print('I am {} years old'.format(20))
print('The number is',5)
print('8. Basic Loop for Printing:')
for i in range(1,6): print(i)